name: Run unit tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Run all unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.*
          check-latest: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug info
        run: |
          go version

      - name: Run tests
        run: go test ./...
